### ISSUE TITLE
8083 bus error

### ISSUE THREAD

**Issue by krainboltgreene** [copperlang/copper#2]
Attempting to run a hello world script breaks.

```
$ copper-llvm helloworld.co
[1]    8083 bus error  copper-llvm helloworld.co
$ cat helloworld.co
function main
  print("Hello, world!")
```

**Comment by mkerbiquet** [comment]
Do you have the same error when just launching the program without parameter? (you should get a 'filename missing' error)

I guess it's an issue with the x86-64 calling convention on Mac OS X (a wrong calling convention won't prevent linking). 

The compiler works fine on Linux x64 and FreeBSD x64, and I thought that Darwin x64 was using the same calling convention. Unfortunately I don't have a Mac OS X to test it, and it will require cross compilation to fix it.

**Comment by krainboltgreene** [comment]
> you should get a 'filename missing' error

Yep, I do!

On Mon, Apr 8, 2013 at 5:15 AM, mkerbiquet notifications@github.com wrote:

> Do you have the same error when just launching the program without
> parameter? (you should get a 'filename missing' error)
> 
> I guess it's an issue with the x86-64 calling convention on Mac OS X (a
> wrong calling convention won't prevent linking).
> 
> The compiler works fine on Linux x64 and FreeBSD x64, and I thought that
> Darwin x64 was using the same calling convention. Unfortunately I don't
> have a Mac OS X to test it, and it will require cross compilation to fix it.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/copperlang/copper/issues/2#issuecomment-16046857
> .

## 

Kurtis Rainbolt-Greene, Hacker
Software Developer
612 S. Flower St.
Los Angeles, CA, 90017

**Comment by mkerbiquet** [comment]
So I must be wrong. 
I'll try to find a 64 bit Mac OS X to debug this.

**Comment by mkerbiquet** [comment]
The compiler is linked correctly. The error comes from the LLVM 64 bit version when the calling convention is not forced to 'cdecl'. With 

```
function .cdecl main
```

it won't crash anymore.

But to do a simple "hello world" program with Copper, you need to import at least a function from the libc as there is no standard library (yet). Just try:

```
import function .c .cdecl puts (*[]Char8)

function .c .cdecl main
  puts ('Hello World')
```

.c forces the C naming convention for symbols ('main' -> '_main')
.cdecl forces the C calling convention (the Copper LLVM version uses the fastcall convention by default)

The compilation should generate a "a.bc" LLVM bitcode file. You can compile it and link it to native code or run it directly with the LLVM interpreter:

```
lli a.bc
```

**Comment by krainboltgreene** [comment]
Way cool, thanks!
